### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by NeverTwice** [IW2-G3/blog#1]
Hey @adrienpayen,

Petit problème, quand je rentre dans la route /article/create j'ai une erreur qui remonte à une vue twig dans les vendors/synfony. Est-ce que ça le fait chez toi aussi?

Btw, j'ai essayé la fonction d'update mais il connait pas update() ici :
`$articleForm = $app['form.factory']->update(ArticleType::class);`

Où je peux trouver les méthodes de form factory?

Thanks

**Comment by adrienpayen** [comment]
`$articleForm = $app['form.factory']->create(ArticleType::class);`

c'est un create et pas un update ;)
